Repository Dansoftowner/14AB-A-plander-docs, pull requests merged in 2023-09, with the labels that each got.

#5 Create guide about writing documentation
  dev-docs/DOCS_WRITING_GUIDE.md
Labels: documentation

#7 added filtering labels
  dev-docs/WORKFLOW.md
Labels: enhancement

#8 Add necessary workflow info
  dev-docs/WORKFLOW.md
Labels: documentation

#12 Code style docs
  dev-docs/CODE_STYLE.md
Labels: documentation

#13 Program documentation
  docs/FEATURES.md
Labels: documentation, attention
